apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: healthsecure-api-secrets

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: healthsecure-api-secrets
    creationPolicy: Owner

  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: healthsecure-secrets
        property: OPENAI_API_KEY

    - secretKey: OPENAI_CHAT_MODEL
      remoteRef:
        key: healthsecure-secrets
        property: OPENAI_CHAT_MODEL

    - secretKey: OPENAI_EMBEDDING_MODEL
      remoteRef:
        key: healthsecure-secrets
        property: OPENAI_EMBEDDING_MODEL

    - secretKey: PINECONE_API_KEY
      remoteRef:
        key: healthsecure-secrets
        property: PINECONE_API_KEY

    - secretKey: PINECONE_INDEX_NAME_OPENAI
      remoteRef:
        key: healthsecure-secrets
        property: PINECONE_INDEX_NAME_OPENAI

    - secretKey: POSTGRES_HOST
      remoteRef:
        key: healthsecure
        property: POSTGRES_HOST

    - secretKey: POSTGRES_USER
      remoteRef:
        key: healthsecure
        property: POSTGRES_USER

    - secretKey: POSTGRES_PORT
      remoteRef:
        key: healthsecure
        property: POSTGRES_PORT

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: healthsecure
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: healthsecure
        property: POSTGRES_DB