apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

resources:
  - ../../base
  - namespace.yaml

images:
  - name: healthsecure-api
    newName: healthsecure-api
    newTag: latest