name: Build and Publish OCI Artifacts
on:
  workflow_dispatch:
  # push:
    # branches:
      # - main
env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: healthsecure-api
  MANIFEST_REPOSITORY: healthsecure-manifests
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API image
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REPOSITORY:$IMAGE_TAG ./main

          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker push \
            $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag in manifests
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd kubernetes/cloud-deployment/overlays/staging

          kustomize edit set image \
          healthsecure-api=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Push Flux OCI artifact (SHA tag)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          flux push artifact \
            oci://$REGISTRY/$MANIFEST_REPOSITORY:$IMAGE_TAG \
            --source=./kubernetes/cloud-deployment/overlays/staging
            --revision=$IMAGE_TAG

      - name: Tag artifact as staging
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          flux tag artifact \
            oci://$REGISTRY/$MANIFEST_REPOSITORY:$IMAGE_TAG \
            --tag staging